### PR TITLE
Drop compatibility code for old Foreman

### PR DESCRIPTION
**Pull request by ekohl**
In 7c2c701efbcef814100878bdb58fd1fa6895c8f3 the minimum Foreman version was raised to 3.1.0 and that doesn't need these workarounds anymore.

### CODE REVIEW

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman_statistics/pull/44 fails in the same way, so this repository's CI is just broken now.

**Comment by ezr-ondrej** [comment]
I've restarted the CI, hopefully it will go green now, I'd love to merge the migration folders now, that there is no reason for them to be separate, but this is still nice cleanup :+1:

**Review by ezr-ondrej — APPROVED** [review]
LGTM, feel free to merge if you don't want to merge the migration folders :)

**Comment by ekohl** [comment]
How would you do that? Is that as simple as `git mv db/migrate_foreman/* db/migrate`?

**Review by ezr-ondrej — APPROVED** [review]
Thanks @ekohl ! 🧡

**Pull request merged**
